sudo: required

services:
  - docker

install: true

script:
  - docker build -t arygmzv90/ffmpeg-raspbian .

after_success: |
  if [ -n "${DOCKER_EMAIL}" ] && [ -n "${DOCKER_TOKEN}" ] && [ "${TRAVIS_PULL_REQUEST}" = 'false' ]
  then
    mkdir -p $HOME/.docker
    echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${DOCKER_TOKEN}\",\"email\":\"${DOCKER_EMAIL}\"}}}" > $HOME/.docker/config.json
    docker push arygmzv90/ffmpeg-raspbian || exit 1
  fi
